### ISSUE TITLE
Mise en forme sections "Explication" des propositions

### ISSUE THREAD

**Issue by DanieLoche** [MieuxVoter/jm#24]
Bonjour,
- -----------
_D'abord un grand bravo et merci pour la plateforme.
C'est clairement ce qu'il manquait jusqu'alors pour populariser ce système de vote._
- -----------
Je ne sais pas s'il s'agit d'un bug ou bien d'une amélioration à apporter,
mais à l'heure actuelle, les informations mises dans les encadrés "Explication sur la proposition" ne conservent aucune mise en forme.
C'est légèrement pénalisant que ne serait-ce les sauts de ligne ne soient pas pris en compte. On ne découvre qu'après publication que ce n'est pas très lisible. Pas possible non plus de mettre en évidence un partie du texte avec du gras/italique voire de la couleur.

**Suggestion :** 
- Ne serait-ce que prendre en compte les sauts de ligne serait pas mal.
- Reconnaitre le Markdown (par exemple) serait l'apotheose.
Je suppose que le plus "complexe" est de gérer la hauteur des boites de vote... Peut-être limiter à 8 lignes maximum pour garantir quelque chose de raisonnable ?

**Comment by oceanBigOne** [comment]
Merci pour votre retour.

J'ai un peu peur des dérives avec la mise en page libre. En revanche, je suis bien d'accord avec l'idée d'au moins prendre en compte les sauts de lignes (et pourquoi pas prévoir quelques opions comme le gras ou l'italique).

**Comment by Draynam** [comment]
Effectivement, les sauts de page semblent indispensables (sinon il faut transformer les champs de saisie en textbox plutôt que des textarea, histoire que les utilisateurs ne soient pas tentés d'en utiliser).

Un moyen d'utiliser des URL serait également vraiment le bienvenu : quasiment tous les votes que je crée s'appuient sur un lien, qu'il s'agisse de la page d'un gîte pour un week-end entre amis, la page d'un restau pour une sortie, la page BGG d'un jeu de société pour une soirée jeux...

Ça peut juste être faire le nécessaire pour que des liens http soient automatiquement reconnus et cliquables, ou avoir une syntaxe type markdown pour générer un lien, ou peut-être le mieux au niveau visuel, ajouter un champ URL en plus des deux champs actuel (on peut alors afficher un simple bouton ou libellé statique plutôt que l'URL complète qui peut alourdir la page de vote).

**Comment by oceanBigOne** [comment]
Je viens d'apporter une petite modification.
- prise en compte des balises HTML <i> et<b>
- prise en compte des sauts de lignes
- transformation automatique des liens saisis en texte en lien html (les liens s'ouvrent dans un nouvel onglet)
