### ISSUE TITLE
Les propositions apparaissent dans le désordre

### ISSUE THREAD

**Issue by Myrkiriad** [MieuxVoter/jm#26]
Bonjour,

Les propositions d'un vote apparaissent dans le désordre sur deux colonnes, sans correspondre à l'ordre avec lequel la saisie des propositions a été réalisée.

Or, quand il y a un ordre implicite évident dans les propositions, cela donne une impression assez étrange que tout soit mélangé. Cela donne une impression d'amateurisme.

Exemple de vote : Quelle quantité préférez vous pour X ? Propositions possibles: Rien du tout, un peu, moyennement, pas mal, beaucoup, énormément, autant que possible.

Suggestion: faire apparaître les propositions dans l'ordre de saisie de l'utilisateur.

Merci pour cette super initiative.

**Comment by 1000i100** [comment]
L'ordre aléatoire me semble une fonctionnalité utile pour ce type de scrutin.
si chacune des options représente une gradation, alors ces options me semble faire double emploi avec la gradation des différentes mentions déjà inclue pour chaque proposition.
Du coup, pour votre cas d'usage, la proposition de gradation des #27 et #30 me semble plus adapté que retirer l'aléatoire dans l'ordre des options.

**Comment by guhur** [comment]
OK je ferme cette issue au profit de #30
