### ISSUE TITLE
Propositions améliorations

### ISSUE THREAD

**Issue by Myrkiriad** [MieuxVoter/jm#27]
Bonjour,

Propositions d'améliorations:

1. Permettre à l'utilisateur de modifier le nom des mentions ("à rejeter", "passable", etc...). Justification: ces mentions ne correspondent pas toujours au formalisme attendu ou peuvent être en décalage avec la question. Exemple: "à rejeter", "passable" peut être vexant pour les personnes ayant portées les propositions. Si la question est "Quelle priorité faut-il donner aux propositions suivantes ? ", les mentions actuelles ne conviennent pas. On préférerait les mentions "Pas prioritaire", "priorité faible", "priorité moyenne", etc....

1. Permettre à l'utilisateur de modifier l'échelle de notation. Aujourd'hui, on met une note entre 0 et 5. L'idée est de permettre de voter sur 10 points au moins. Éventuellement plus. Justification: Une échelle de 0 à 5 ne permet pas toujours d'avoir une granularité suffisante.

Bon courage.

**Comment by 1000i100** [comment]
la partie proposition variable de la #30 me semble aller dans le même sens.

**Comment by guhur** [comment]
OK je ferme cette issue au profit de #30
