### ISSUE TITLE
Calcule du jugement majoritaire sur un seuil à 50%

### ISSUE THREAD

**Issue by ysaenger** [MieuxVoter/jm#29]
Dans le cas ou un candidat à 50% de très bien et 50% de à rejeter, le jugement calculé en résultat est à rejeté par ce site. Dans ce cas, la barre de 50% à jugé très bien. Ce qui est délicat, c'est que en fonction de ce qu'à voté l'électeur sur la mention suivante.
Exemple
Candidat A : 50% de Bien, 50% de Passable => Passable au lieu de Bien
Candidat B : 50% de Très bien, 50% de A rejeter => A rejeter au lieu de très bien

**Comment by guhur** [comment]
C'est la règle du jugement majoritaire qui est comme ça. Prendre la médiane basse peut crééer des résultats paradoxaux mais dans des cas très rares (mesure quasi nulle), mais ce procédé a également de nombreux avantages, comme la résistance aux stratégies électorales.

Pour approfondir la discussion, vous pouvez vous référer au livre de [Laraki et Balinski](https://mitpress.mit.edu/books/majority-judgment) ou contacter Rida Laraki par mail directement.
