### ISSUE TITLE
A proposal is not rated or ranked

### ISSUE THREAD

**Issue by fforster** [MieuxVoter/jm#34]
Hello, I created a proposal with 11 options. For some reason one of the options does not appear to have evaluations or a ranking, even though it is shown as an option when accessing the vote link. See image below, first row in the table at the bottom does not appear to have evaluations.

![error](https://user-images.githubusercontent.com/5090828/70106771-4a092080-1623-11ea-8463-a92e30ab39f4.png)

**Comment by guhur** [comment]
Hi,

I just tried with 11 options and it seems to work. Could you double-check?

By the way, we are working on a new version (https://github.com/MieuxVoter/mvfront-react). Do you think you could help us with Spanish translations?

Best,
Pierre

**Comment by fforster** [comment]
Hi, I couldn't reproduce the issue either, but I thought it would be important to understand what went wrong. If it helps I can send you the vote links, it was only an experiment. I would be happy to help with the translations to Spanish, I'm already looking at it :)
Cheers, Francisco
