### ISSUE TITLE
[Bloquant] Limite à 6 votants, le 6ème vote clôt le scrutin mais n'est plus visible par la suite

### ISSUE THREAD

**Issue by Draynam** [MieuxVoter/jm#35]
Reproduit deux fois dans des conditions identiques. L'anomalie est bloquante !

Sur un scrutin avec une limite à 6 votants, lorsque le 6ème votant soumet son vote, il est immédiatement redirigé vers une page de résultats qui est correcte, elle prend bien en compte les 6 votes.

Cependant, toutes les ouvertures suivantes du lien du scrutin mènent vers une page de résultats ne présentant que les 5 premiers résultats (facilement visible aux noms des votants, ainsi qu'à la répartition des pourcentages qui tombe juste en multiples de 20%).

Voici deux exemples, quasiment identiques présentant ce comportement :
https://jugementmajoritaire.net/vote/1591c8feae3c39e1a5ee61be9f9c305cff6fe0555cef
https://jugementmajoritaire.net/vote/15842b7b933b72668c4c74b505f13209a54cdea5fe0d

**Comment by oceanBigOne** [comment]
Merci !

Je regarde ça dès que possible.

**Comment by oceanBigOne** [comment]
**Explication :**

> Une fois le vote terminé, un fichier de cache est généré afin de "figer" les résultats et d'améliorer les temps de réponses.
> Je n'ai pas réussi à provoquer le problème mais je l'ai bien constaté avec vos liens. Mon intuition et que vous avez réussi à générer le cache avant que le vote soit fini (peut-être en utilisant le lien d'administration?) alors que cela ne devrait pas être possible.

Dans le doute je viens de faire le nécessaire pour m'assurer que le résultat en cache soit recalculé après chaque nouveau vote (quelque soit l'état du vote).

Je viens également de forcer la régénération de la page de résultat sur les deux liens donnés

Merci encore !

**Comment by Draynam** [comment]
Effectivement, les deux scrutins avaient un lien de consultation des résultats partiels, et ce lien avait été ouvert très régulièrement, à priori au moins une fois après chaque vote.
Merci pour la correction ! Ce site est génial pour organiser des scrutins à jugement majoritaire, bien plus "propre" visuellement et plus rigoureux que celui que j'utilisais précédemment :)
