### ISSUE TITLE
Vote de Valeur ?

### ISSUE THREAD

**Issue by 1000i100** [MieuxVoter/jm#38]
Bonjour, je serais intéressé de voir un dépouillement alternatif en vote de valeur histoire de visualiser les différences et pourqoui pas d'annoncer lors d'un vote quel dépouillement sera utilisé pour la prise de décision.

En outre, je cherche toutes ressources comparative entre ces deux modes de vote (Jugement Majoritaire et Vote de Valeur)

**Comment by guhur** [comment]
Bonjour,

Nous ne prévoyons pas pour le moment d'inclure le vote par valeurs dans notre système de dépouillement. En effet, l'association cherche à montrer que le vote majoritaire est limité et qu'un meilleur mode de vote est possible. Le discours devient trop compliqué à notre goût si on commence à comparer toutes les manières de voter.

De plus, plusieurs sites existent déjà pour proposer des animations comparant les différents systèmes de vote. Et autrement, on peut toujours se référer au livre du [Majority Judgment](https://mitpress.mit.edu/books/majority-judgment), Laraki et Balinski posent assez clairement les différences, avantages et faiblesses de chaque mode de vote.
