### ISSUE TITLE
Token pour limiter à 1 vote = 1 votant

### ISSUE THREAD

**Issue by 1000i100** [MieuxVoter/jm#39]
Bonjour, je serais intéressé par un système d'émission de token à distribuer aux potentiels votant (par email ou autre, via la plateforme ou à la main par l'initiateur du vote).

L'idée serait de pouvoir limiter à 1 vote par votant, sans pouvoir identifier qui à voté quoi (sauf à être administrateur d'une instance et donc d'avoir toutes les information en base de données).

L'autre bonus pourrait être de visualisé le taux de participation / d'abstention en indiquant le nombre de token émis/distribué, et le nombre de vote effectué.

Concrètement, cela reviendrait à utiliser les pseudo des votant comme liste blanche, les générer automatiquement et aléatoirement, et les ajouter à l'url pour qu'ils soient automatiquement renseigné.

ça vous parle comme fonctionnalité ajoutable ?

**Comment by guhur** [comment]
Bonjour,

C'est un chantier que nous sommes en train d'entreprendre. Nous souhaitons intégrer Belenios comme back-end pour stocker les votes. [Belenios](https://interstices.info/vote-par-internet/) a été prisé de nombreuses fois pour ses capacités de gestion de l'authentification. 

Si vous souhaitez pour contribuer à cette partie du projet, nous pourrions nous appeler. 

Bonne journée,

**Comment by 1000i100** [comment]
Merci, passionnante découverte que Belenios !

Pour l'instant, je suis à fond sur un autre projet, donc je ne me sens pas de contribuer au delà qu'en proposant quelques tickets, mais d'ici quelques temps, pourquoi pas oui !

**Comment by guhur** [comment]
OK ! Je ferme cette issue alors au profit de https://github.com/MieuxVoter/mvapi/issues/10
