### ISSUE TITLE
Erreur dans le calcul du classement ?

### ISSUE THREAD

**Issue by jpiel** [MieuxVoter/jm#42]
Bonjour, j'ai remarqué une erreur dans le calcul du classement.

<img width="1115" alt="ErreurVote" src="https://user-images.githubusercontent.com/12051594/79553547-eeed3d00-809c-11ea-97a4-92acdfc5434b.png">

Le résultat indique l'ordre suivant : 
1: D  2: F  3: E  4: B  5: C  6: A

Alors que ça devrait être : 
1: D  2: C  3: E  4: F  5: B  6: A

En tout cas si on considère le mode de classement cité ci-dessous. Si ce n'est pas le cas, quel est le mode utilisé pour départagé des résultats équivalents ? 

> D'accord, mais comment départager deux candidats qui obtiennent la même mention majoritaire ? S’il n'y avait eu que A et B dans l'exemple précédent, comment déterminer qui gagne ? On rajoute alors des indices + ou - à la mention majoritaire. C'est assez simple, si le pourcentage des mentions au-dessus de la mention médiane est supérieur au pourcentage des mentions en dessous de la médiane, alors on met "+", et on met "-" si c'est l'inverse.
> Dans l'exemple précédent, A est "Passable +" car la somme de Excellent+Très-Bien+Bien+Assez-Bien (48) est supérieure à la somme de A rejeter+Insuffisant (17). Pour B, c'est "Passable -" car la somme des premiers (30) est inférieure à la somme des seconds (45). A est donc devant B.
> 
> Et si ça ne suffit pas ? Si les deux candidats ont la même mention avec "+", celui qui aura le meilleur pourcentage de mentions supérieures à sa médiane gagnera, parce qu'on considère qu'il y a plus de personnes qui le notent mieux. Si les deux candidats ont la même mention "-", celui qui aura le plus faible pourcentage de mentions inférieures à la médiane gagnera parce qu'on considère qu'il y a moins de personnes qui le notent moins bien.

**Comment by oceanBigOne** [comment]
Bonjour,

Merci pour votre retour.

Tout d'abord, je tiens à préciser que nous (avec l'association MieuxVoter) travaillons sur une nouvelle version qui est déjà accessible à l'adresse suivante : [https://app.mieuxvoter.fr/](https://app.mieuxvoter.fr/)

Ce n'est pas cet algorithme là qui est implémenté ici (c'est un calcul et non pas une methode avec des indices), mais le résultat devrait être le même ! 

Je pense que le problème vient de :

>  celui qui aura le meilleur pourcentage de mentions supérieures à sa médiane gagnera, parce qu'on considère qu'il y a plus de personnes qui le notent mieux.

Qui donne le même résultat si on ecrit :

> celui qui aura le meilleur pourcentage de mentions supérieures **ou égale à sa mention** médiane gagnera, parce qu'on considère qu'il y a plus de personnes qui le notent mieux.

**Avec cette lecture, on a :**
D est gagnant.
**Ensuite on a :**
A+,B+,C+,E+,F+ 

on peut ensuite dire :
_"Au moins 67% des personnes juge que F est au moins Assez bien"
"Au moins 63% des personnes juge que E est au moins Assez bien"
"Au moins 57% des personnes juge que B est au moins Assez bien"
"Au moins 54%? des personnes juge que C est au moins Assez bien"
"Au moins 53%? des personnes juge que A est au moins Assez bien"

Du coup, l'ordre est assez clair et je pense que l'algorithme utilisé est équivalent à cette lecture.

Je vais donc demander un avis extérieur supplémentaire ! (merci encore pour cette remontée d'information)

**Comment by jpiel** [comment]
Merci de la réponse. 

Effectivement on n'a pas la même manière de départager après.
Je pense que dans le calcul il est important de considérer les mentions supérieures et pas supérieures ou égales. Car on parle de ceux qui notent mieux que la médiane.
C'est d'ailleurs la méthode préconisée par les "auteurs du jugement majoritaire" (Rida Laraki et Michel Balinski) dans leur rapport.

En fait, c'est très bien expliqué dans [cet article](https://sciencetonnante.wordpress.com/2016/10/21/reformons-lelection-presidentielle/)


> Imaginons que les deux meilleurs candidats aient obtenu exactement la même mention majoritaire, disons « Assez Bien ». Comment les départager ? Une manière simple consiste à simplement déclarer vainqueur celui dont le pourcentage cumulé des mentions supérieures ou égales (AB, B, TB et Excellent) est le plus élevé. C’est simple, mais les auteurs Rida Laraki et Michel Balinski proposent une autre manière de procéder.
> 
> On peut en effet nuancer les mentions : prenez un candidat, considérez le pourcentage des gens qui ont attribué une mention strictement meilleure (ici : B, TB et Excellent) et comparez le au pourcentage des gens qui ont attribué une mention strictement inférieure (ici : à rejeter, Insuffisant, Passable). Si le premier est plus élevé, vous nuancez la mention en « + », si le second est plus élevé, vous nuancez la mention en « -« . Et bien évidemment pour une mention identique, le « + » bat le « -« .
> 
> En cas de nouvelle égalité, pour une égalité de mention « + » on regarde le % des gens ayant attribué une mention strictement supérieure. Celui avec le plus gros pourcentage gagne. Pour une égalité de mention « -« , on regarde le % des gens ayant attribué une mention strictement inférieure, dans ce cas celui avec le pourcentage le plus faible gagne.
> 
> Ce raffinement des mentions permet de traiter les cas d’égalité, et d’après les auteurs, il donne un résultat plus représentatif que de regarder simplement le pourcentage cumulé.
> 
> J’ai eu la chance de pouvoir interviewer Rida Laraki et Michel Balinski sur ces questions, qu’ils en soient remerciés ! Et j’avoue que je trouve cette méthode pour départager les ex-aequos un chouilla compliquée, même si on peut argumenter qu’elle est meilleure. Je me demande si le gain de « perfection » de cette méthode justifie de compliquer le système de vote, surtout que l’on parle déjà d’un changement démocratique majeur.

**Comment by jpiel** [comment]
En fait j'ai refait mes calculs, et je m'étais trompé, j'avais oublié la prise en compte du + et -, mais je n'arrive toujours pas au même résultat.

J'ai : A (AB-)  B (AB-) C (AB-) D (B-) E (AB) F (AB-)

D reste gagnant, pas de soucis.
Le deuxième est E car il n'est pas AB- il est juste AB (il est pile au milieu)

Ensuite, pour départager les notation en "-" il faut regarder les pourcentages inférieurs.
On a donc F puis B. A et C étant encore à égalité, on regarde les pourcentages supérieurs : et donc on a C puis A.

L'ordre devrait donc être D E F B C A.

(enfin je crois :) )

**Comment by oceanBigOne** [comment]
Pouvez-vous me donner les dix derniers caractères du lien du vote afin que l'on puisse contrôler avec les chiffres exactes ? (je partagerai les informations du vote avec des personnes de l'association)

**Comment by jpiel** [comment]
Bonjour,

Voici les 10 derniers caractères :
f981c1c716

Mais entre temps les votes ont évolué, et ça ne reflète plus 
vraiment ce que je disais dans le message. Je peux par contre resimuler 
un vote avec des résultats équivalents, il n’y avait qu’entre 10 
et 15 votants.



-- 
Jayce Piel  --  jayce.piel@gmail.com
Responsable Informatique F.F.Tir

**Comment by oceanBigOne** [comment]
Ça serait super si cela ne vous embête pas, comme ça on pourrait étudier le cas "concret"

**Comment by jpiel** [comment]
Ok, je fais ça ce soir ou dans le week-end.

**Comment by rnollet** [comment]
Ceci m’a l’air assez fidèle :
https://jugementmajoritaire.net/vote/2460397bd60920a2fba7ea8a1ba6290e1c4d8add5ab6

**Comment by jpiel** [comment]
Oui, c'est les chiffres que j'ai également...

**Comment by rnollet** [comment]
Le classement du site est effectivement celui du jugement majoritaire, et peut
être justifié _a posteriori_ comme suit :
- Entre les 6 options : D a la mention majoritaire (MM) « Bien » (B) tandis que
  tous les autres ont « Assez bien » (AB), ce qui place D en tête du
  classement.
- Entre A, B, C, E et F : A et C sont à seulement 0.5 voix près d’avoir
  « Passable » (P), alors que 0.5 voix de différence ne change la MM d’aucune
  des 3 autres options. Ils sont donc derrière B, E et F.
- Entre B, E et F : B est à seulement 1.5 voix près d’avoir P, alors que 1.5
  voix de différence ne changent pas les MM de E ou F. Donc B est derrière E et
  F.
- Entre E et F : E est à 2.5 voix près d’avoir B, il est aussi à 2.5 voix près
  d’avoir P, alors que 2.5 voix de différence ne changent pas la MM de F. C’est
  un cas particulier qui n’arrive pas souvent. Dans ce cas, entre les deux,
  c’est la mention inférieure qui est considérée en priorité. Ici on considère
  donc que E plus proche de P, et il passe derrière F.
- Entre A et C : on met de côté le fait qu’ils sont tous deux à 0.5 voix près
  d’être P, puisque ça ne permettra pas de les départager. C est alors à 1.5
  voix près d’être B, alors que 1.5 voix de différence ne permet pas à A d’être
  B. Donc C est devant A.

Conclusion : ((A < C) < (B < (E < F))) < D

**Comment by rnollet** [comment]
Il y a une animation visuelle qui serait d’une grande aide pour expliquer ce
genre de choses : c’est que la ligne verticale centrale, qui marque la médiane
de la série, se divise en deux lignes verticales identiques, qui s’éloignent
horizontalement, l’une à gauche et l’autre à droite, à la même vitesse.  Dès
qu’une de ces lignes rencontre un changement de mention pour un des candidats,
il se passe quelque chose. Ici ça donnerait ceci :
1. Au départ les deux lignes sont confondues sur la médiane. La mention
   majoritaire sépare D des autres. Le classement est, pour l’instant, `{A, B,
   C, E, F} < D`
2. Le premier changement de mention rencontré a lieu à distance 0.5 de la
   médiane (en nombre de voix) : c’est celui où A et C descendent de AB à P. Le
   classement devient `{A, C} < {B, E, F} < D`
3. Deuxième changement, à 1.5 voix de la médiane : B descend de B à P et C
   monte de AB à B. Quand les deux lignes rencontrent un changement de mention
   en même temps, on regarde d’abord ce qui arrive du côté des mentions
   inférieures :
   - B descend de B à P. Le classement devient `{A, C} < B < {E, F} < D`
   - C monte de AB à B. Le classement devient `A < C < B < {E, F} < D`
4. À 2.5 voix de la médiane :
   - A descend de P à I, mais ça n’a plus d’importance puisque A n’est plus à
     départager d’avec une autre option. Le classement reste `A < C < B < {E, F}
     < D`
   - E descend de AB à P. Le classement devient `A < C < B < E < F < D`. On a
     fini.
   - E monte de AB à B. Mais c’est pris en compte après celle d’avant, parce
     que quand des choses se produisent en même temps, on regarde d’abord ce
     qui arrive à la ligne qui va vers les mentions inférieures. E n’est déjà
     plus à départager d’avec une autre option, donc le classement ne change
     pas.

Je n’ai totalement pas les connaissances nécessaires pour réaliser une telle animation, mais j’ai l’intuition que ce serait un outil très puissant pour faire comprendre comment fonctionne le JM.

**Comment by jpiel** [comment]
Ok, je comprends bien la logique sur le calcul, ça se tient, mais ce n’est pas vraiment en accord avec la méthode préconisée par Rida Laraki et Michel Balinski. 

Je trouve cette méthode plus compliquée que la leur. Surtout à expliquer. 
C’est peut-être par contre plus facile à coder, je n’ai pas réfléchi à l’algo pour la méthode « d’origine ». 
Et je ne suis pas sûr que le classement soit plus cohérent avec cette méthode. Le fait de preferer les mentions supérieures si on a un + ou les mentions inférieures si on a un - me semble plus cohérent que de prioriser tout le temps les mentions inférieures sur les supérieures. 

Mais ce n’est que mon avis. 

Bon, du coup, ce n’est pas un bug mais un choix de méthode, je vais fermer le ticket alors.

**Comment by oceanBigOne** [comment]
@rnollet J'ai commencé à travailler sur cette animation de mon côté. Je manque de temps (et un peu de compétence), mais je suis convaincu également par son utilité.

**Comment by rnollet** [comment]
@jpiel J’aimerais réussir à être convaincant sur deux points :

1. La méthode que j’ai présentée produit exactement les résultats du JM tel que défini par ses auteurs. Donc est complètement en accord avec les méthodes qu’ils présentent et ne produit pas un classement plus ou moins cohérent mais le *même* classement. La méthode implémentée dans le site est probablement encore une autre méthode. Elle produit aussi le même résultat.

2. En particulier, le jugement majoritaire (= cette méthode = la méthode du site) ne priorise pas _a priori_ les mentions inférieures sur les supérieures. Mais il le fait dans des cas très particuliers, qui ont peu de chance d’arriver quand le nombre de votants est grand.

## La méthode des jauges majoritaires

Par rapport au premier point : Rida Laraki et Michel Balinski présentent dans la section 14.1 du livre une approximation de la méthode générale, fondée sur la notion de jauge majoritaire. C’est celle que tu mentionnais : les `+` et `-`. Dans notre exemple, cette méthode donne les jauges majoritaires suivantes :

Option | Jauge majoritaire (supérieur, médiane, inférieur)
-- | --
A | `(3, AB -, 9)`
B | `(4, AB -, 8)`
C | `(8, AB -, 9)`
D | `(4, B -, 6)`
E | `(7, AB -, 7)`
F | `(5, AB -, 6)`

Chacune de ces jauges est à lire de la manière suivante : A, par exemple, a la mention majoritaire AB ; 3 voix qui lui donnent une mention supérieure à AB et 9 voix qui lui donnent une mention inférieure à AB ; puisque 9 >= 3, le signe de la mention majoritaire est `-`. Ici ces jauges permettent d’établir le classement suivant :

Rang | Option  | Jauge majoritaire (supérieur, médiane, inférieur)
-- | -- | --
1 | D | `(4, B -, 6)`
2 | F | `(5, AB -, 6)`
3 | E | `(7, AB -, 7)`
4 | B | `(4, AB -, 8)`
5 et 6 | A _vs._ C | `(3, AB -, 9)` _vs._ `(8, AB -, 9)`

Deux remarques importantes :
1. Le signe de `M` dans `(p, M, q)` est `+` quand `p > q` et `-` quand `p <= q`. Ce n’est pas tout-à-fait symétrique. En particulier E, pour lequel il y a autant de voix qui veulent augmenter sa MM que de voix qui veulent la diminuer, a une mention signée `-`.
2. Comme, dans ce cas, tous les candidats ont une MM signée `-`, ceux qui ont la même MM sont départagés en regardant le nombre de voix qui veulent diminuer leur MM, c’est-à-dire les troisièmes membres des triplets. Si leur mention était signée `+`, on les départagerait avec le premier membre du triplet.

Cette méthode ne permet toujours pas de départager A et C, qui ont tous les deux `AB -`, et qui ont tous les deux 9 voix en faveur d’une MM inférieure.

**/!\\** Attention à un piège : la méthode *n’est pas*, dans ces cas, de les départager en regardant les premiers éléments des triplets. Pas toujours. Pas en général.

La méthode, dans ce cas, est, le temps de les départager, d’amalgamer leur mention immédiatement inférieure à leur mention majoritaire. (On amalgame avecla mention inférieure parce qu’ils sont `-`. S’ils étaient `+` on amalgamerait la mention immédiatement supérieure.) Elles deviennent donc :

Option | Jauge majoritaire généralisée
-- | --
A | `(3, AB/P -, 7)`
C | `(8, AB/P +, 4)`

donc, à cause des signes, C passe devant A.

Cette possibilité d’égalité et cette dernière étape sont souvent volontairement omise par les introductions au JM, parce que quand le nombre d’électeurs est grand ça arrive rarement, et qu’une introduction a envie de rester simple.

## Biais en faveur des mentions inférieures

Je reviens sur les deux remarques que j’ai faites dans la section précédente. Il y a bien deux phénomènes à distinguer :
- Dans cet exemple les égalités sont départagées, presque à chaque fois, par le nombre de votants qui veulent diminuer la MM de l’option. C’est seulement parce que dans cet exemple ils sont plus nombreux que ceux qui veulent l’augmenter. Ça n’est pas un biais _a priori_ de la méthode.
- Dans le cas de E, il y a autant de votants qui veulent augmenter sa MM que de votants qui veulent la diminuer. Que devrait être le signe de sa MM dans ce cas ? On pourrait avoir envie d’introduire un troisième signe `0` pour ces cas-là. Mais le JM dit que dans ce cas sa MM est signée `-`. Ce léger biais du JM en faveur des mentions inférieures permet d’obtenir une propriété très agréable du JM : deux candidats ne peuvent être _ex-æquo_ que s’ils ont exactement le même profil de notes. Autrement dit : si les candidats ont des profils de notes différents, le JM fournit toujours un classement total des candidats. Si on utilisait un `0`, on perdrait cette propriété.

## Un exemple pour résumer

Si l’ordre des mentions est inversé, en considérant que « Très bien » est en fait la pire mention et que « À rejeter » est en fait la meilleure, quel classement obtient-on ? Arrives-tu à te convaincre que, dans ce cas, le classement devient `D < E < F < B < C < A` ?

**Comment by jpiel** [comment]
Alors je suis confus, dans les notes que je m’étais faites il y a 3 ans quand j’ai étudié le système (et que j’ai relu hier pour me rafraîchir la mémoire, j’avais noté p>q et p<q, j’avais zappé le <=, et donc je partais du principe que si c’était égal il n’y avait ni plus ni moins. 

C’est pour ça que dans mon classement je mettais E en 2e. Et je comprends mieux mon erreur. 

Pour le reste on est d’accord. 

Bon, au final tout ça m’aura permis de corriger mes notes. :)
